// <auto-generated />
using System;
using Bomb.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bomb.Infra.Data.Migrations
{
    [DbContext(typeof(BombContext))]
    [Migration("20211210155626_Update DisarmAttempt")]
    partial class UpdateDisarmAttempt
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Bomb.Domain.Models.CuttedWire", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ColorEnum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DisarmAttemptId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DisarmAttemptId");

                    b.ToTable("CuttedWires");
                });

            modelBuilder.Entity("Bomb.Domain.Models.DisarmAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("DisarmAttempts");
                });

            modelBuilder.Entity("Bomb.Domain.Models.CuttedWire", b =>
                {
                    b.HasOne("Bomb.Domain.Models.DisarmAttempt", "DisarmAttempt")
                        .WithMany("CuttedWires")
                        .HasForeignKey("DisarmAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DisarmAttempt");
                });

            modelBuilder.Entity("Bomb.Domain.Models.DisarmAttempt", b =>
                {
                    b.Navigation("CuttedWires");
                });
#pragma warning restore 612, 618
        }
    }
}
